name: python-release-minor
on:
  workflow_run:
    workflows: [ "python-test" ]
    types:
      - completed
    branches:
      - 'main'

jobs:
  advance-minor:
    if: github.event.pull_request.merged == true && ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        pip install bumpver build
    - name: Update minor version
      run: |
        bumpver update --minor


