name: python-release
on:
  workflow_run:
    workflows: [ "python-test" ]
    types:
      - completed
    branches:
      - 'main'

jobs:
  advance-and-release:
    if: ${{ contains(github.event.head_commit.message, 'bump version')}} && ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        pip install build
    - name: Build
      run: |
        python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}