name: python-test
on: workflow_call
jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      code-files-changed: ${{ steps.filter.outputs.code-files }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          list-files: 'json'
          filters: |
            code-files:
              - 'src/**'
              - 'test/**'
  unit-test:
    needs: changes
    runs-on: ${{ matrix.os }}
    if: ${{ needs.changes.outputs.code-files-changed == 'true' }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with unittest
        run: |
          python -m unittest
